In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [3]:
np.sqrt(11)
print("Minimun ",np.amin([15,30,67,18]))

Minimun  15


In [4]:
np.ceil(29.1)

30.0

In [5]:
np.ceil(np.sqrt(10))

4.0

In [6]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [7]:
np.array([5,9,13])

array([ 5,  9, 13])

In [8]:
type([5,9,13])

list

In [9]:
a=np.array([[1,2],[3,4],[4,5]])
print("Type - ",a.dtype)

print("\n",a)

Type -  int32

 [[1 2]
 [3 4]
 [4 5]]


In [10]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
a=[1,2]
c=np.array(a)
print(c)

[1 2]


In [12]:
type(c)

numpy.ndarray

In [13]:
import numpy as np

In [14]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type/class of this object : ",type(mat))
print("Here is the marks \n------\n",mat,"\n-----------")
print("print dimension of this matrix : ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size of the matrix : ",mat.size)#size shows total number elements
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column
print("Data Type of the matrix ; ",mat.dtype)#shoes which type

Type/class of this object :  <class 'numpy.ndarray'>
Here is the marks 
------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int32


In [15]:
a=np.arange(10)

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print("Every 5th number from 50 in reverse order \n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5  0]


In [18]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [19]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


In [20]:
print("vector of zeros \n------------")
print(np.zeros([5]))

vector of zeros 
------------
[0. 0. 0. 0. 0.]


In [21]:
print("vector of zeros \n---------")
print(np.zeros([5,6]))

vector of zeros 
---------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
print("vector of ones \n------------")
print(np.ones([5,6]))

vector of ones 
------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [23]:
x=np.arange(30).reshape(5,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [24]:
np.random.seed(6) # Each seed number will generate similar data
print("Random number genration (from uniform distribution)")
print(np.random.rand(10,6))

Random number genration (from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [25]:
print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [ 6  9 14 13 17 19 15 15 15  9]


In [26]:
print("\n Random integer matrix")
print(np.random.randint(1,30000,(6,7)))


 Random integer matrix
[[17767 20336 13946  5831 18333 23859 23494]
 [ 9840 13091 19932 22813 22477  6712 26415]
 [ 1629  4047 18646 24128 19309 14509 28418]
 [12269 24210  1628 26120 10710  5861 15283]
 [18649 12256  5545 14414 22568 29305 21329]
 [18667  3149 29998 13997 27769 26448  3386]]


In [28]:
def generate_otp():
    otp=np.random.randint(1000,10000,1)
    print("Your Otp is ",otp)
    user_otp=int(input("Enter Your OTP Here"))
    if otp==user_otp:
        print("Log in Sucessfully")
    else:
        print("Your OTP is invalid")

In [29]:
generate_otp()

Your Otp is  [2021]


Enter Your OTP Here 2021


Log in Sucessfully


In [31]:
emp_salary=np.random.randint(8,70,10)

In [32]:
emp_salary

array([40, 20, 54, 54, 31, 30, 56, 47, 35, 45])

In [33]:
np.clip(emp_salary,a_min=20,a_max=50)

array([40, 20, 50, 50, 31, 30, 50, 47, 35, 45])

In [34]:
import numpy as np
from numpy.random import randint as ri

In [35]:
a=ri(1,99,30)
print(a)

[34 89 42 28 91 23 52 96 72 72  6 68 73 80 40 43  6 58 97 24 88 46 32 17
 70 36  3 15 21 30]


In [36]:
b=a.reshape(2,3,5)
print(b)

[[[34 89 42 28 91]
  [23 52 96 72 72]
  [ 6 68 73 80 40]]

 [[43  6 58 97 24]
  [88 46 32 17 70]
  [36  3 15 21 30]]]


In [37]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[58  1 73 63 19]
 [98 87 73 89 74]
 [33 72 17 38 47]
 [90 45 57 46 38]
 [74 61  2 66 26]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 1 19 58 63 73]
 [73 74 87 89 98]
 [17 33 38 47 72]
 [38 45 46 57 90]
 [ 2 26 61 66 74]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[33  1  2 38 19]
 [58 45 17 46 26]
 [74 61 57 63 38]
 [90 72 73 66 47]
 [98 87 73 89 74]]


In [38]:
arr=np.arange(13,30)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [39]:
print("Element of 7th index is =",arr[7])

Element of 7th index is = 20


In [40]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [41]:
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [42]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [43]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [44]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:

print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [46]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [47]:

print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]


In [49]:
mat[0,2]=200

In [50]:
mat

array([[  1,   2, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [51]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[35 47 96 94 84]
 [26 78 64 76 22]
 [59 57 24 36 74]]


In [52]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [96 94 84 78 64 76 59 57 74]


In [53]:
print(np.where(mat==98))

(array([], dtype=int64), array([], dtype=int64))


In [54]:
age=50
np.where(age>68,'Retired','Still Working')

array('Still Working', dtype='<U13')

In [55]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrics of Single digit number \n---------------\n",mat1)
print("\n 2st Matrics of Single digit number \n---------------\n",mat2)


 1st Matrics of Single digit number 
---------------
 [[3 3 6]
 [1 8 7]
 [7 1 6]]

 2st Matrics of Single digit number 
---------------
 [[5 9 3]
 [5 3 4]
 [5 1 6]]


In [56]:
print("\n Division \n---------------------\n",mat1/mat2)


 Division 
---------------------
 [[0.6        0.33333333 2.        ]
 [0.2        2.66666667 1.75      ]
 [1.4        1.         1.        ]]


In [57]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[-1 -9 12]
 [-7 18 13]
 [11  1  6]]


In [58]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [60]:
y=start+add_rows

In [61]:
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [62]:
new_row=add_rows.T

In [63]:
new_row

array([[1],
       [0],
       [2]])